# Generated by Django 4.2.9 on 2024-01-12 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_remove_student_teachers_studentteacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='teachers',
            field=models.ManyToManyField(related_name='students', to='school.teacher'),
        ),
        migrations.DeleteModel(
            name='StudentTeacher',
        ),
    ]
